### ISSUE TITLE
Mobile bug: tapping an open dropdown doesn't close it

### ISSUE THREAD

**Issue by elimisteve** [illright/attractions#133]

**Comment by elimisteve** [comment]
As mentioned here: https://old.reddit.com/r/sveltejs/comments/ieexhf/attractions_a_new_minimal_ui_components_library/g2n7e0k/

**Comment by aabounegm** [comment]
Details:
This is specific only to the mentioned dropdown ("Components" in the [mobile navigation bar](https://github.com/illright/attractions/blob/master/docs/src/containers/docs/mobile-navigation.svelte)), not the dropdown component in general. This is due to it being opened depending on the `change` event of the `<Tab>` instead of the `click` event of a button (as is the normal use case). Clicking the same tab twice doesn't change the value of the selected tab, and therefore the dropdown is not toggled again.
