### ISSUE TITLE
Warning: Found 2 elements with non-unique id #null

### ISSUE THREAD

**Issue by illright** [illright/attractions#167]
TextFields and other components that have the `id` as a prop default to that ID being `null` for some reason, which is the reason of warnings in the console like:
```
Found 2 elements with non-unique id #null
```

**Comment by aabounegm** [comment]
This seems to be an issue with Sapper's rendering (though I couldn't find any related open issue on their repo). This is because if I navigate to https://illright.github.io/attractions/docs/components/text-field by first going to https://illright.github.io/attractions/docs/ and then clicking on "TextField", I don't get this error. Even when going to that page directly, the `null` id is only present in the page source (<kbd>CTRL + U</kbd>), but not actually on the element if you inspect it through the DevTools.

**Comment by illright** [comment]
Yeah, when I investigated, I also came to the conclusion that Sapper renders out the `null`-valued props and Svelte removes them afterwards. Been meaning to create an MCVE and open an issue to Sapper

**Comment by illright** [comment]
Follow https://github.com/sveltejs/sapper/issues/1664 for progress on this issue
