### ISSUE TITLE
Autocomplete does not pass slots on to AutocompleteField

### ISSUE THREAD

**Issue by sallaben** [illright/attractions#182]
Hi, I am hoping to use Autocomplete and set my own values for the slots in AutocompleteField. 

```
  <Autocomplete 
    {getOptions}
    bind:selection>
    <span slot="more-options">
      more
    </span>
    <span slot="too-many-options">
      too many
    </span>
  </Autocomplete>
```

However the Autocomplete implementation does not allow for slots to be passed through. 

Is it possible to pass through slots when present in this component? Thank you!

**Comment by illright** [comment]
It's not possible to pass slots to `Autocomplete` since it is meant to be an opinionated bundle of functionality that can be simply plugged in and ready to go. The `AutocompleteField` component is exposed exactly for the cases when some more customization is desired. So technically you could implement your own `Autocomplete` on top of `AutocompleteField`. It's not that much code, [actually](https://github.com/illright/attractions/blob/master/attractions/autocomplete/autocomplete.svelte).

But can you describe your customization usecase a little more? If all you want is just to change the text in the labels, perhaps we could expose that text through props.

**Comment by sallaben** [comment]
Thank you, these are good pointers. I wanted to be able to pass text or a component instance in, and in some cases disable the piece of functionality entirely. It sounds like I might be a good candidate for implementing my own autocomplete component with the sub-components you've provided.
