### ISSUE TITLE
Autocomplete-option fails when query includes regex pattern

### ISSUE THREAD

**Issue by sallaben** [illright/attractions#184]
For example, the autocomplete fails on the input `+` because js regex interprets that as 'repeat the last character'.

To reproduce, query `+++` on the documentation page https://illright.github.io/attractions/docs/components/autocomplete

is this intended? If so, the documentation could include that detail. Or maybe this behavior could be exposed as a boolean flag.

**Comment by illright** [comment]
No, that's certainly not intended. The issue is [right here](https://github.com/illright/attractions/blob/master/attractions/autocomplete/autocomplete-option.svelte#L6), where we don't escape the regex, which is a shortcoming indeed. We'll fix this in the upcoming patch release. Thanks for the report!

**Comment by sallaben** [comment]
You are awesome! Thanks for getting to these issues. As I familiarize myself more with attractions I will try to submit my own enhancements and bug fixes but I really appreciate your hard work in the meantime.
