### ISSUE TITLE
No `Select` component?

### ISSUE THREAD

**Issue by geoidesic** [illright/attractions#266]
I notice there is Dropdown but it's not quite the same thing. Select elements on form are pretty standard and you've got the basics of it done for autocomplete. Am I just missing something or is this an omission?

**Comment by illright** [comment]
Well, technically, it's an omission, but a somewhat intentional one, however, we're flexible on that. The reason why we don't include such a component as of now is because it's rather broad in its usage, so it would be a challenging tradeoff between customizability and ease of use.

Besides, I believe that a `Select` component is not unique in its functionality, and in the cases that I have encountered, it wasn't the best form element. Good candidates for replacement would be [`RadioChipGroup`](https://illright.github.io/attractions/docs/components/radio-chip-group) and [`Autocomplete`](https://illright.github.io/attractions/docs/components/autocomplete), as you've mentioned.

Of course, the above is strictly limited to my development experience, so I would appreciate if you could demonstrate a use-case that makes the `Select` shine. And how would you like to use/customize this component?

**Comment by geoidesic** [comment]
Um.. just look at this page. There are 9 distinct selects, or drop-down menus (largely the same thing) on it that aren't auto-completes! So there's 9 use cases for you. I can't imagine building anything without them. You even have one on your documentation site; image attached.

<img width="212" alt="Screenshot 2021-06-05 at 18 54 19" src="https://user-images.githubusercontent.com/4637995/120900916-8447e980-c62f-11eb-8cf7-6923e7d4710c.png">

A select is also a standard HTML form element, so not being able to style that up nicely using your UI library of choice feels naff. If you're going to style the input, may as well offer styling for select element too. People use them all the time in forms.

Usage and customisation
I don't think autocomplete and select should be different elements. I think one configurable component is all one needs. See quasar again for what I think is an optimal implementation, they split Menu and Select into two separate things: select being for forms, menus being for interface, which is a traditional split which I support although I've seen other libraries that are more cavalier in grouping these two things as one component, while Attractions seems to be missing both.

https://quasar.dev/vue-components/select
https://quasar.dev/vue-components/menu

I'm amazed to hear tales of a developer who's never had to use a select! :)

**Comment by aabounegm** [comment]
I agree that a select component would be useful, but unfortunately don't currently have the time to implement one. Maybe I'll get to it after exams, but in the meanwhile, PRs are welcome.
