### ISSUE TITLE
[Bug Report] A copy-paste issue on official site

### ISSUE THREAD

**Issue by AtharvaKamble** [illright/attractions#281]
Found this nice library and went on the installation guide. The copy-paste feature for the Step 1 doesn't copy the command but the title of the section either i.e. Terminal. I have provided image for the same. Thanks!

Its on https://illright.github.io/attractions/docs/installation/

PS: I tested on Firefox and Brave.

Edit: link

![image](https://user-images.githubusercontent.com/60008419/128626863-bce5e3c9-4b4c-4a5c-90bf-094609378771.png)

**Comment by aabounegm** [comment]
Thank you for the report.
The culprit seems to be this line:
https://github.com/illright/attractions/blob/84b8aa62dc169408d6f154829605bdb8dca8b51a/docs/src/components/docs/copyable-code.svelte#L19

It only check for the existence of a file name, not the terminal. Should probably be something like:
```js
    const preIndex = filename == null && terminal === false ? 0 : 1;
```

I'm currently away from PC for a couple of days, so if you (or @illright) wouldn't mind creating that PR, I'd happily merge it :)

**Comment by AtharvaKamble** [comment]
Sure, I'll create a PR. Feel free to assign me here.

**Comment by AtharvaKamble** [comment]
I was trying to setup attractions and ran into this error stating that it `global.scss` cannot find `~attractions/_variables`. (Picture attached)

What I did after cloning:
- `npm i` in root directory
- `npm i` in docs directory
- `npm run docs:dev` from root directory

Any idea where am I going wrong?

![image](https://user-images.githubusercontent.com/60008419/128629799-68aff4f7-328f-4002-ba06-863fa0215759.png)

**Comment by illright** [comment]
Yeah, I think I've seen this before. Try using Yarn for now, this problem skills disappear. We are soon moving to pnpm, and with that should come a fix for this problem
