### ISSUE TITLE
Issue with Icon in Accordion component 

### ISSUE THREAD

**Issue by esoteloferry** [illright/attractions#300]
Hi, 
Great UI, thanks. 

Following accordion example:
https://illright.github.io/attractions/docs/components/accordion

There is a "ChevronDownIcon" component that is not exported by attractions. Then if I try to run it crashes. 

- Where does the icon come from? 
- Is there some docs for icon setup?

**Comment by aabounegm** [comment]
All icons used in the docs come from [Feather Icons](https://feathericons.com/), using the [svelte-feather-icons](https://www.npmjs.com/package/svelte-feather-icons) package. It is not a dependency of the library itself as to not install packages users may not need, but we did copy a few of the icons to use for the default content of some slots. You can check the documentation of the linked library to learn more about it.

**Comment by aabounegm** [comment]
1. The `ml` class is one that is written in the Attractions docs only and simply adds a `margin-left`. It can be found here: https://github.com/illright/attractions/blob/6b9089ce61c85a476584af3a258e71277d38d278/docs/static/css/global.scss#L41-L43
2. Styles in Svelte are scoped by default, so you would need to use `:global` modifiers. You can check the DevTools to figure out which rules are taking precedence (due to scoping)

**Comment by illright** [comment]
If you want to customize some component **A** from Attractions, it's best to put this customization in the style tag of your own component **B** that uses component **A**, and leave the `theme.scss` file to simply declare variables.

Here's how it could look like:
* `theme.scss`:

   ```scss
  @forward '~attractions/_variables' with (
     $main: hsl(250, 69%, 61%),
  );
  ```
* `component-b.svelte`:

  ```svelte
  <script>
    import { AccordionSection } from 'attractions';
  </script>
  
  <div class="anything-you-like">
    <AccordionSection />
  </div>
  
  <style>
    .anything-you-like :global .accordion-chevron {
      margin-left: 2em;
    }
  </style>
  ```

Here's what's happening: when you prepend `:global` to a selector, this selector loses scoping, which means that it can apply not only to DOM elements defined within your component (in the example above it would only be the `<div>`) but to any other component that you use. However, scoping is important and useful in preventing style leakage, which is why I wrapped the `AccordionSection` in a `<div>` in the example above. The CSS selector is only partially global – the `.anything-you-like` part will still be scoped, so there won't be any style leakage outside of this component, but your selector will still reach the `.accordion-chevron` defined inside Attractions.

**Comment by esoteloferry** [comment]
> ```svelte
> <script>
>   import { AccordionSection } from 'attractions';
> </script>
> ```

Thanks for detailed reply, I replicate what you proposed : 

- AccordionSection.svelte (created this component in my project)

`<script>
    import { AccordionSection } from "attractions";
</script>

<div class="section">
    <AccordionSection />
</div>

<style>
    .section :global .accordion-chevron {
        margin-left: 2rem;
    }
</style>
`

But now there is no information inside the accordion:
![Screen Shot 2021-09-09 at 20 46 59](https://user-images.githubusercontent.com/32800604/132745018-6b18e300-b4e8-4a9b-a263-73c98eca51db.png)

Previous result (following doc example) and no custom css:
![Screen Shot 2021-09-09 at 20 48 50](https://user-images.githubusercontent.com/32800604/132745246-f983ef2e-db95-48f5-8864-5badea62500f.png)

It looks like that in my new component I have to setup slots, input parameters , etc? , not sure :S

**Comment by illright** [comment]
The code I provided above is a valid Svelte component, but not an example of valid usage of the `Accordion` component. Keep the `<style>` tag, but add the stuff from the docs of the `Accordion` and you should see it working properly.

**Comment by esoteloferry** [comment]
Great!, I got the idea. I need to wrap it so I can add the style I want. Then I need to provide data that the new component will render. 

Next issue I encounter (now not related to css , but with typescript so let me know if it is ok here) is that I would like to provide the data as a typed input. But as soon as I enabled typescript <script lang="ts"> , then I get 2 errors with the example shown in AccordionSection from docs : 

```
<script lang="ts">
  import { Button, Accordion, AccordionSection } from "attractions";
  import Icon from "../../components/Icon.svelte";
  import { chevron_down } from "../svgs";

  type item = { name: string };
  type folder = { name: string; list: (item | folder)[] };
  let topics: [folder] = [
    {
      name: "Topic 1",
      list: [{ name: "1dof" }, { name: "2dof" }],
    },
  ];
</script>

<div class="section">
  <Accordion let:closeOtherPanels>
    <AccordionSection on:panel-open={closeOtherPanels} let:toggle>
      <div slot="handle">
        <Button on:click={toggle}>
          open first panel
          <Icon path={chevron_down} size="20" class="accordion-chevron" />
        </Button>
      </div>
      First panel
    </AccordionSection>
    <AccordionSection
      on:panel-open={closeOtherPanels}
      label="just text is enough"
    >
      Second panel
    </AccordionSection>
  </Accordion>
</div>

```
The issue is in: 
- closeOtherPanels: [ts 2345] [E] Argument of type '(e: CustomEvent<AccordionSection>) => void' is not assignable to parameter of type '(e: CustomEvent<{ close: () => void; toggle: () => void; }>) => void'.
  Types of parameters 'e' and 'e' are incompatible.
    Type 'CustomEvent<{ close: () => void; toggle: () => void; }>' is not assignable to type 'CustomEvent<AccordionSection>'.
      Type '{ close: () => void; toggle: () => void; }' is missing the following properties from type 'AccordionSection': $set, $on, $destroy, $prop_def, and 5 more.

- toggle : [ts 2339] [E] Property 'toggle' does not exist on type '{}'.
