### ISSUE TITLE
[help wanted] How to use this via Snel (deno based svelte handling...)

### ISSUE THREAD

**Issue by michael-spengler** [illright/attractions#308]
https://github.com/crewdevio/Snel

This would improve UI dev efficiency enourmously imo. 

All ideas on that are very welcome.

**Comment by michael-spengler** [comment]
And to make the challenge more concrete / project specific:   

We have developed a volatility farmer which can be checked here: https://openforce.de/ 

This does not look too cool yet as I follow the order: 1. make it work 2. make it beautiful :) 

In order to make it beautiful we want to use attractions in order to make our vofarm (volatility farming) look a bit like our design drafts: https://www.figma.com/file/BXL9ESnJsqgLTkGfhxnaSS/VOLATILITY-FARMING?node-id=0%3A1

We want to continue to use the latest most promising technologies in this project as it is a long term project for which we also check collaboration options with https://uniswap.org - we have applied for https://unigrants.org in this respect... 

So we would be happy to serve as pilot customers for making attractions deno-ready ...

**Comment by michael-spengler** [comment]
... connecting snel + attractions via https://github.com/crewdevio/Snel/issues/40

**Comment by illright** [comment]
Okay, I looked over some stuff. Honestly, it's still hard for me to wrap my head around how UI development could be done in Deno (and more importantly, why :D). I've only ever seen Deno as a cool replacement for Node in backend and command-line tools.

I've discovered that Carbon Components [were ported](https://github.com/crewdevio/Snel-carbon) to Snel by Snel developers. Looked around their code base to see how they handle styles... only to find out that they don't. Well, Carbon Components in general promotes an external stylesheet (which I'm not too keen on, tbh). Seeing as Attractions is packaged together with styles, I could see the issues of porting it.

Seems like Snel supports Sass (albeit in a rather hidden away way), but it doesn't support what `svelte-preprocess` does with `<style src="...">`. As such, a quick first step could be to just stuff all the styles inside the actual components and see what difference that makes. However, I'm kind of hesitant to make such experiments because it is completely unclear to me how Snel works, what's in store for it, etc. I'm looking forward to hearing what the Snel devs have to say on the issue you've linked above. If you manage to create a proof-of-concept with an archtecture similar to that of Attractions (most importantly, an external variables file) and get it working, I'll be glad to try to implement it here. Until then, we will probably not do any restructuring of Attractions to avoid wasted effort if nothing comes of it.

**Comment by michael-spengler** [comment]
Hi @illright. Thanks for the infos which I can absolutely understand. 
I'm also excited on what the Snel devs will recommend when it comes to reusing UI kits like attractions.

I will close the issue at hand in order not to spam your open issues list. Maybe we'll pick this up one day...
