### ISSUE TITLE
Add Dropdown Menu component 

### ISSUE THREAD

**Issue by YugoCode** [illright/attractions#338]
Hey! :)

First of all I wanted to thank you for creating the prettiest UI kit in my eyes! You make Svelte projects look great 🔥

The only component I'm missing is a dropdown menu, as described here: https://material.io/components/menus#usage

You already have a Dropdown component, but I think this is rather a tooltip, as described here: https://material.io/components/tooltips

Do you plan to add the dropdown menu component?

Thanks again! ❤️

![dropdown](https://user-images.githubusercontent.com/21986752/150928308-1aa0928b-c9c4-4300-874a-e753f91ba304.jpg)

**Comment by illright** [comment]
Hi. Thanks for your kind words :)

I'm not sure I understand how you think the [Dropdown](https://illright.github.io/attractions/docs/components/dropdown) component is what Material calls a Tooltip. In my opinion, we have a [Popover](https://illright.github.io/attractions/docs/components/popover) component which resembles the tooltip much more closely. I do agree that the examples in the documentation are a bit misleading in terms of the content of the dropdowns, but it can contain not only text, but full-blown interactive components like buttons.

I see the component you're missing. Other people have referred to it as a Select, and its development is "tracked" in #266. The reason why "tracked" is in quotes is because we're not actively working to add new features currently for several reasons. However, as I mentioned in that linked issue, I believe that a Select is not unique in its functionality, so maybe you could work around this limitation with other components? And you're always welcome to contribute this component (although I've heard that Select components are notoriously difficult to get right in terms of accessibility).

**Comment by aabounegm** [comment]
Given the lack of follow-up response for about 4 months now, I'll close this issue
