### ISSUE TITLE
Implement disabling certain days for the calendar

### ISSUE THREAD

**Issue by illright** [illright/attractions#34]
So that one could specify an array of days or ranges (unbounded too)

**Comment by aabounegm** [comment]
What about days/ranges that are included two times in the same month view, such as in the following screenshot (from the [docs](https://illright.github.io/attractions/docs/components/calendar))?
![image](https://user-images.githubusercontent.com/11016151/128430649-f07ff2bf-1ae4-4127-b636-8002ce559c13.png)

I was imagining the prop type as `disabled: Array<number | {start?: number; end?: number}>`, where the numbers mean only the day number in the month (leading to the problem above). How about the same interface but with `Date` objects instead of `number`, where only the date (not time) will be considered? Additionally, if the start or end may be left out, what happens if both are left out? Is it ignored or does it mean "all days are disabled"?

**Comment by illright** [comment]
Yeah, I think it should be `Date` objects, not `number`. About both the start and the end being disabled – I guess we can take it as "all days are disabled" not to clutter the computation logic too much.
