### ISSUE TITLE
svelte-preprocess 5 is available

### ISSUE THREAD

**Issue by canadaduane** [illright/attractions#362]
I'm new and was following the directions from the readme to get started. I believe `svelte-preprocess` version 4 is required at the present time, but "latest" now defaults to 5.0. It may be helpful to others to update the readme to something like this:

```
npm install --save-dev svelte-preprocess@4 sass postcss
# -- or --
yarn add --dev svelte-preprocess@4 sass postcss
# -- or --
pnpm add --save-dev svelte-preprocess@4 sass postcss
```

**Comment by aabounegm** [comment]
Did you face any problems when installing `v5`? It seems to me that the breaking changes shouldn't affect us since we recommend installing `sass` and not `node-sass`, and while we don't explicitly specify a minimum node version, I doubt anyone who uses Svelte(Kit) has Node.js earlier than `v14`.

Anyways, after the WIP migration to SvelteKit (particularly, the migration from Sass to CSS), we should hopefully not need any of these dependencies.

**Comment by canadaduane** [comment]
It was more of a warning than a problem:

![image](https://user-images.githubusercontent.com/129/210091516-b604d7e6-e8c0-4918-8117-c16a13ca4ee7.png)

**Comment by aabounegm** [comment]
Ah, right, this should be harmless. We just need to update the allowed version range in the peer dependencies.
